FROM node:20 

WORKDIR /usr/src/app

COPY ./package*.json ./
# COPY ./package-lock.json ./

RUN npm install --force

COPY . .

# RUN npm run build
# CMD ["npm","run","build"]  

# FROM node:20-alpine

# WORKDIR /usr/src/app

# COPY --from=build /app/build .

EXPOSE 3000

CMD ["npm","run","dev"]


