version: '3'
services:
  mongodb:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - data:/data/db
  
  backend:
    image: shaunak09/backend:1.0
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - Database_Url=mongodb://data:27017/Chatbot
      - Port=5000

  frontend:
    image: shaunak09/frontend:1.0
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  data: