version: '3'
services:
  mongodb:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - data:/data/db
  
  backend:
    image: backend:1.0
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    mage: frontend:1.0
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  data: